default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['HOST'] %>
  username: root
  password: password
  pool: 5

development:
  <<: *default
  database: warehouse_development
  password: password

test:
  <<: *default
  database: warehouse_test

production:
  <<: *default
  database: warehouse_production
  username: warehouse
  password: <%= ENV['HERO_DATABASE_PASSWORD'] %>
